// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/examplev1/example_api.proto

package examplev1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/examplev1/example_api.proto", fileDescriptor_a48ddc38c1fdac41) }

var fileDescriptor_a48ddc38c1fdac41 = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0x33, 0x84, 0xb1, 0xe2, 0x13, 0x0b,
	0x32, 0xf5, 0xc0, 0x72, 0x42, 0x42, 0xa5, 0x79, 0x99, 0xe5, 0x99, 0xc5, 0xa9, 0x7a, 0x50, 0x29,
	0xbd, 0x32, 0x43, 0x23, 0x1e, 0x2e, 0x2e, 0x57, 0x08, 0xcf, 0x31, 0xc0, 0xd3, 0x89, 0x3b, 0x8a,
	0x13, 0x6e, 0x40, 0x12, 0x1b, 0x58, 0x97, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xc3, 0x2d,
	0x4f, 0x5a, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleAPIClient is the client API for ExampleAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleAPIClient interface {
}

type exampleAPIClient struct {
	cc *grpc.ClientConn
}

func NewExampleAPIClient(cc *grpc.ClientConn) ExampleAPIClient {
	return &exampleAPIClient{cc}
}

// ExampleAPIServer is the server API for ExampleAPI service.
type ExampleAPIServer interface {
}

// UnimplementedExampleAPIServer can be embedded to have forward compatible implementations.
type UnimplementedExampleAPIServer struct {
}

func RegisterExampleAPIServer(s *grpc.Server, srv ExampleAPIServer) {
	s.RegisterService(&_ExampleAPI_serviceDesc, srv)
}

var _ExampleAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uniwise.example.v1.ExampleAPI",
	HandlerType: (*ExampleAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/examplev1/example_api.proto",
}
